# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
          key: ${{ matrix.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Build
        run: |
          yarn 
          yarn electron:build

      - name: Upload build executable program
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            ${{ github.workspace }}/dist_electron/switch-hosts*.dmg
            ${{ github.workspace }}/dist_electron/switch-hosts*.exe
            ${{ github.workspace }}/dist_electron/switch-hosts*.AppImage
          retention-days: 1
